const state = { images: [], filtered: [], index: -1, current: null, boxes: [], selected: -1, activeClass: 'rice', undo: [], redo: [], previous: null, drag: null };
const $ = (id) => document.getElementById(id);
async function api(path, options) { const response = await fetch(path, options); const value = await response.json(); if (!response.ok) throw new Error(value.error || '请求失败'); return value; }
function updateProgress() { $('progress').textContent = `${state.filtered.filter(item => item.status === 'labelled').length} / ${state.filtered.length}`; }
function applyFilter() { const filter = $('filter').value; state.filtered = state.images.filter(item => filter === 'all' || item.status === filter); renderList(); updateProgress(); if (!state.filtered.length) { state.index = -1; state.current = null; renderCanvas(); return; } state.index = Math.max(0, Math.min(state.index, state.filtered.length - 1)); loadCurrent(); }
function renderList() { $('image-list').innerHTML = state.filtered.map((item, index) => `<button class="image-item ${index === state.index ? 'selected' : ''}" data-index="${index}"><span>${item.name}</span><small>${item.status}<br>${item.box_count}框</small></button>`).join(''); document.querySelectorAll('.image-item').forEach(button => button.onclick = () => { state.index = Number(button.dataset.index); loadCurrent(); }); }
async function loadCurrent() { if (state.index < 0 || !state.filtered[state.index]) return; state.current = state.filtered[state.index]; const value = await api(`/api/labels/${encodeURIComponent(state.current.name)}`); state.boxes = value.boxes || []; state.previous = null; state.selected = -1; state.undo = []; state.redo = []; renderList(); renderCanvas(); }
function imageElement() { const image = new Image(); image.src = `/media/${encodeURIComponent(state.current.name)}`; return image; }
function renderCanvas() { const canvas = $('canvas'); const empty = $('empty'); if (!state.current) { canvas.width = canvas.height = 0; empty.style.display = 'block'; return; } empty.style.display = 'none'; const image = imageElement(); image.onload = () => { const scale = Math.min(1, (canvas.parentElement.clientWidth - 20) / image.naturalWidth, (window.innerHeight - 250) / image.naturalHeight); canvas.width = image.naturalWidth * scale; canvas.height = image.naturalHeight * scale; canvas.dataset.scale = scale; const context = canvas.getContext('2d'); context.drawImage(image, 0, 0, canvas.width, canvas.height); state.boxes.forEach((box, index) => { context.strokeStyle = index === state.selected ? '#ffcf54' : (box.class_name === 'rice' ? '#49d3a6' : '#ff9278'); context.lineWidth = 2; context.strokeRect(box.x * scale, box.y * scale, box.width * scale, box.height * scale); context.fillStyle = context.strokeStyle; context.fillText(`${box.class_name} ${index + 1}`, box.x * scale + 4, box.y * scale + 15); }); }; }
function pushUndo() { state.undo.push(JSON.stringify(state.boxes)); state.redo = []; }
function imagePoint(event) { const rect = $('canvas').getBoundingClientRect(); const scale = Number($('canvas').dataset.scale || 1); return { x: Math.max(0, (event.clientX - rect.left) / scale), y: Math.max(0, (event.clientY - rect.top) / scale) }; }
function hitBox(point) { for (let i = state.boxes.length - 1; i >= 0; i--) { const box = state.boxes[i]; if (point.x >= box.x && point.x <= box.x + box.width && point.y >= box.y && point.y <= box.y + box.height) return i; } return -1; }
function finishBox(point) { if (!state.drag) return; const start = state.drag.start; const box = { class_name: state.activeClass, x: Math.min(start.x, point.x), y: Math.min(start.y, point.y), width: Math.abs(point.x - start.x), height: Math.abs(point.y - start.y) }; state.drag = null; if (box.width >= 4 && box.height >= 4) { pushUndo(); state.boxes.push(box); } renderCanvas(); }
$('canvas').addEventListener('mousedown', (event) => { const point = imagePoint(event); const hit = hitBox(point); if (hit >= 0) { state.selected = hit; } else { state.drag = { start: point }; state.selected = -1; } renderCanvas(); }); $('canvas').addEventListener('mousemove', (event) => { if (state.drag) renderCanvas(); }); $('canvas').addEventListener('mouseup', (event) => finishBox(imagePoint(event)));
document.querySelectorAll('.class').forEach(button => button.onclick = () => { state.activeClass = button.id; document.querySelectorAll('.class').forEach(item => item.classList.toggle('active', item === button)); });
$('delete').onclick = () => { if (state.selected < 0) return; pushUndo(); state.boxes.splice(state.selected, 1); state.selected = -1; renderCanvas(); }; $('undo').onclick = () => { if (!state.undo.length) return; state.redo.push(JSON.stringify(state.boxes)); state.boxes = JSON.parse(state.undo.pop()); state.selected = -1; renderCanvas(); }; $('redo').onclick = () => { if (!state.redo.length) return; state.undo.push(JSON.stringify(state.boxes)); state.boxes = JSON.parse(state.redo.pop()); state.selected = -1; renderCanvas(); }; $('copy').onclick = () => { if (!state.previous) return; pushUndo(); state.boxes = JSON.parse(JSON.stringify(state.previous)); renderCanvas(); }; $('skip').onclick = () => { pushUndo(); state.status = 'ambiguous'; saveCurrent(); }; $('save').onclick = saveCurrent;
async function saveCurrent() { if (!state.current) return; const status = state.status || (state.boxes.length ? 'labelled' : 'skipped'); await api(`/api/labels/${encodeURIComponent(state.current.name)}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ boxes: state.boxes, status }) }); state.previous = JSON.parse(JSON.stringify(state.boxes)); state.images = await api('/api/images').then(value => value.images); state.status = null; applyFilter(); }
$('prev').onclick = () => { if (state.index > 0) { state.index--; loadCurrent(); } }; $('next').onclick = () => { if (state.index + 1 < state.filtered.length) { state.index++; loadCurrent(); } }; $('filter').onchange = applyFilter;
api('/api/images').then(value => { state.images = value.images; applyFilter(); }).catch(error => { $('empty').textContent = error.message; });
